//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCReportGen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonInfo
    {
        public int UId { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string LessonName { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
