//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCReportGen.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ltclk_eteacherEntities : DbContext
    {
        public ltclk_eteacherEntities()
            : base("name=ltclk_eteacherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LessonInfo> LessonInfoes { get; set; }
        public virtual DbSet<MoodlePaymentInfo> MoodlePaymentInfoes { get; set; }
        public virtual DbSet<MoodleSubjectInfo> MoodleSubjectInfoes { get; set; }
        public virtual DbSet<SubjectInfo> SubjectInfoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserRoleInfo> UserRoleInfoes { get; set; }
        public virtual DbSet<VIdeoInfo> VIdeoInfoes { get; set; }
        public virtual DbSet<VideoTxnInfo> VideoTxnInfoes { get; set; }
    }
}
