//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCReportGen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoTxnInfo
    {
        public int UId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> VideoViewCount { get; set; }
        public Nullable<int> Active { get; set; }
        public int VideoID { get; set; }
    }
}
